#!/bin/bash

curl -s https://downloads.dockerslim.com/releases/1.29.0/dist_linux.tar.gz | tar xvz -C /tmp
chmod 711 /tmp/dist_linux/docker-slim
/tmp/dist_linux/docker-slim build ${DOCKER_REPO:-${IMAGE_NAME}}

echo IMAGE_ID=$IMAGE_ID
echo VERSION=$VERSION
echo DOCKER_REPO=$DOCKER_REPO
echo SOURCE_COMMIT=$SOURCE_COMMIT
export REPO=${DOCKER_REPO:-${IMAGE_ID}}
export VER=${SOURCE_COMMIT:-${VERSION:-latest}}-slim
echo REPO=$REPO
echo VER=$VER
docker tag $IMAGE_NAME.slim $REPO:$VER
docker push $REPO:$VER