#!/bin/bash

curl -s https://downloads.dockerslim.com/releases/1.29.0/dist_linux.tar.gz | tar xvz -C /tmp
chmod 711 /tmp/dist_linux/docker-slim
/tmp/dist_linux/docker-slim build $IMAGE_NAME
docker tag $IMAGE_NAME.slim $IMAGE_NAME